version: "3.3"
services:
  zomboid:
    build: .
    volumes:
      - ./pzserver:/opt/pzserver
      - ./steam:/root/.steam
    ports:
      - 16261:16261
      - 16262:16262
    stdin_open: true 
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        steamcmd +runscript /app/zomboid.txt
        /opt/pzserver/start-server.sh
        
# to access console:
# docker-compose exec zomboid bash