version: "3.3"
services:
  zomboid:
    build: .
    working_dir: /opt/pzserver
    volumes:
      - ./pzserver:/opt/pzserver
      - ./steam:/root/.steam
      - .:/app
    ports:
      - 16261:16261
      - 16262:16262
      - 8766:8766
      - 8767:8767
      - 27015:27015
    command:
      - /bin/sh
      - -c
      - |
        bash start-server.sh -adminpassword zombieadmin -servername woahdude

#- bash start-server.sh -adminpassword zombieadmin
#- /opt/pzserver/start-server.sh -adminpassword zombieadmin
#default admin: zombieadmin