version: "3.3"
services:
  zomboid:
    build: .
    volumes:
      - ./pzserver:/opt/pzserver
      - ./steam:/root/.steam
      - .:/app
    ports:
      - 16261:16261
      - 16262:16262
    command:
      - /opt/pzserver/start-server.sh
        
#default admin: zombieadmin